server:
  port: 8085

app:
  integration:
    ml:
      # URL do servidor Python (IA)
      url: "http://127.0.0.1:5000/predict"
      threshold-prob: 0.5

    clima:
      # URL da API StormGlass
      url: "https://api.stormglass.io/v2/weather/point"
      # O Spring vai ler a variável CLIMA_API_KEY que você configurou no IntelliJ
      key: "${CLIMA_API_KEY}"
      coords:
        # Coordenadas fixas para teste (Galeão - RJ)
        gig-lat: -22.81
        gig-lon: -43.24

    noticias:
      url: "http://localhost:8085/api/noticias"